
[entities]

	[entities.hidebehind]
		#True if this entity can despawn freely when no players are nearby.
		doDespawn = false
		#The spawn chance compared to other entities (typically between 6-20)
		#Range: 1 ~ 9999
		weight = 5
		#Whether to use spawn costs in spawning or not
		useSpawnCosts = false
		#Maxmimum cost the spawning algorithm can accrue for this entity
		#Range: 0.01 ~ 9999.0
		maxCost = 10.0
		#Setting to true enables biome based variant spawning. This will make this entity choose variants based on the biome they spawn in. (No longer affects spawn eggs as it did in the past, only natural spawns)
		biomeBasedVariants = true
		#Must be greater or equal to min value!
		#Range: 1 ~ 9999
		maxGroup = 1
		#Disables natural spawning
		doSpawning = true
		#Must be greater than 0
		#Range: 1 ~ 9999
		minGroup = 1
		#Cost to spawning algorithm per entity spawned
		#Range: 0.01 ~ 9999.0
		costPer = 1.0
		#Enter biome Resource Locations. Supports modded biomes.
		spawnBiomes = ["minecraft:taiga", "minecraft:wooded_hills", "minecraft:jungle_edge", "minecraft:giant_tree_taiga", "minecraft:flower_forest", "minecraft:dark_forest", "minecraft:snowy_taiga_mountains", "minecraft:tall_birch_hills", "minecraft:taiga_hills", "minecraft:giant_spruce_taiga_hills", "minecraft:birch_forest_hills", "minecraft:dark_forest_hills", "minecraft:forest", "minecraft:snowy_taiga", "minecraft:tall_birch_forest", "minecraft:birch_forest", "minecraft:giant_tree_taiga_hills", "minecraft:wooded_mountains", "minecraft:giant_spruce_taiga", "minecraft:taiga_mountains", "minecraft:snowy_taiga_hills"]

	[entities.hirschgeist]
		#True if this entity can despawn freely when no players are nearby.
		doDespawn = false
		#The spawn chance compared to other entities (typically between 6-20)
		#Range: 1 ~ 9999
		weight = 2
		#Whether to use spawn costs in spawning or not
		useSpawnCosts = false
		#Maxmimum cost the spawning algorithm can accrue for this entity
		#Range: 0.01 ~ 9999.0
		maxCost = 10.0
		#Must be greater or equal to min value!
		#Range: 1 ~ 9999
		maxGroup = 1
		#Disables natural spawning
		doSpawning = true
		#Must be greater than 0
		#Range: 1 ~ 9999
		minGroup = 1
		#Cost to spawning algorithm per entity spawned
		#Range: 0.01 ~ 9999.0
		costPer = 1.0
		#Enter biome Resource Locations. Supports modded biomes.
		spawnBiomes = ["minecraft:taiga", "minecraft:wooded_hills", "minecraft:jungle_edge", "minecraft:giant_tree_taiga", "minecraft:flower_forest", "minecraft:dark_forest", "minecraft:snowy_taiga_mountains", "minecraft:tall_birch_hills", "minecraft:taiga_hills", "minecraft:giant_spruce_taiga_hills", "minecraft:birch_forest_hills", "minecraft:dark_forest_hills", "minecraft:forest", "minecraft:snowy_taiga", "minecraft:tall_birch_forest", "minecraft:birch_forest", "minecraft:giant_tree_taiga_hills", "minecraft:wooded_mountains", "minecraft:giant_spruce_taiga", "minecraft:taiga_mountains", "minecraft:snowy_taiga_hills"]

	[entities.moth]
		#How many moths required to destroy a torch - Disabled if set to 0
		#Range: > 0
		moths_to_destroy_torch = 5
		#True if this entity can despawn freely when no players are nearby.
		doDespawn = true
		#The spawn chance compared to other entities (typically between 6-20)
		#Range: 1 ~ 9999
		weight = 10
		#Whether to use spawn costs in spawning or not
		useSpawnCosts = false
		#Maxmimum cost the spawning algorithm can accrue for this entity
		#Range: 0.01 ~ 9999.0
		maxCost = 10.0
		#Must be greater or equal to min value!
		#Range: 1 ~ 9999
		maxGroup = 3
		#Disables natural spawning
		doSpawning = true
		#Must be greater than 0
		#Range: 1 ~ 9999
		minGroup = 1
		#Cost to spawning algorithm per entity spawned
		#Range: 0.01 ~ 9999.0
		costPer = 1.0
		#Enter biome Resource Locations. Supports modded biomes.
		spawnBiomes = ["minecraft:taiga", "minecraft:wooded_hills", "minecraft:jungle_edge", "minecraft:giant_tree_taiga", "minecraft:flower_forest", "minecraft:dark_forest", "minecraft:snowy_taiga_mountains", "minecraft:tall_birch_hills", "minecraft:taiga_hills", "minecraft:giant_spruce_taiga_hills", "minecraft:birch_forest_hills", "minecraft:dark_forest_hills", "minecraft:forest", "minecraft:swamp_hills", "minecraft:snowy_taiga", "minecraft:tall_birch_forest", "minecraft:swamp", "minecraft:birch_forest", "minecraft:giant_tree_taiga_hills", "minecraft:wooded_mountains", "minecraft:giant_spruce_taiga", "minecraft:taiga_mountains", "minecraft:snowy_taiga_hills"]

	[entities.zotzpyre]
		#True if this entity can despawn freely when no players are nearby.
		doDespawn = true
		#The spawn chance compared to other entities (typically between 6-20)
		#Range: 1 ~ 9999
		weight = 30
		#Whether to use spawn costs in spawning or not
		useSpawnCosts = false
		#Maxmimum cost the spawning algorithm can accrue for this entity
		#Range: 0.01 ~ 9999.0
		maxCost = 10.0
		#Must be greater or equal to min value!
		#Range: 1 ~ 9999
		maxGroup = 1
		#Disables natural spawning
		doSpawning = true
		#Must be greater than 0
		#Range: 1 ~ 9999
		minGroup = 1
		#Cost to spawning algorithm per entity spawned
		#Range: 0.01 ~ 9999.0
		costPer = 1.0
		#Enter biome Resource Locations. Supports modded biomes.
		spawnBiomes = ["minecraft:beach", "minecraft:jungle_edge", "minecraft:flower_forest", "minecraft:shattered_savanna_plateau", "minecraft:mountains", "minecraft:giant_spruce_taiga_hills", "minecraft:birch_forest_hills", "minecraft:modified_jungle", "minecraft:modified_jungle_edge", "minecraft:snowy_mountains", "minecraft:mushroom_field_shore", "minecraft:snowy_beach", "minecraft:swamp_hills", "minecraft:shattered_savanna", "minecraft:snowy_taiga", "minecraft:swamp", "minecraft:giant_tree_taiga_hills", "minecraft:taiga_mountains", "minecraft:snowy_taiga_hills", "minecraft:taiga", "minecraft:wooded_hills", "minecraft:jungle", "minecraft:giant_tree_taiga", "minecraft:dark_forest", "minecraft:modified_badlands_plateau", "minecraft:mountain_edge", "minecraft:snowy_taiga_mountains", "minecraft:desert_hills", "minecraft:ice_spikes", "minecraft:tall_birch_hills", "minecraft:taiga_hills", "minecraft:jungle_hills", "minecraft:eroded_badlands", "minecraft:dark_forest_hills", "minecraft:forest", "minecraft:tall_birch_forest", "minecraft:stone_shore", "minecraft:gravelly_mountains", "minecraft:modified_wooded_badlands_plateau", "minecraft:birch_forest", "minecraft:wooded_mountains", "minecraft:snowy_tundra", "minecraft:giant_spruce_taiga", "minecraft:modified_gravelly_mountains"]

	[entities.wisp]
		#True if this entity can despawn freely when no players are nearby.
		doDespawn = false
		#The spawn chance compared to other entities (typically between 6-20)
		#Range: 1 ~ 9999
		weight = 13
		#Whether to use spawn costs in spawning or not
		useSpawnCosts = false
		#Maxmimum cost the spawning algorithm can accrue for this entity
		#Range: 0.01 ~ 9999.0
		maxCost = 10.0
		#Must be greater or equal to min value!
		#Range: 1 ~ 9999
		maxGroup = 3
		#Disables natural spawning
		doSpawning = true
		#Must be greater than 0
		#Range: 1 ~ 9999
		minGroup = 1
		#Cost to spawning algorithm per entity spawned
		#Range: 0.01 ~ 9999.0
		costPer = 1.0
		#Chance of wisp being hostile (soul stealer). Chance is 1/x, where x is the value specified. 0 is no chance, 1 is 100% chance, 2 is 50% chance, etc
		#Range: > 0
		hostile_chance = 8
		#Enter biome Resource Locations. Supports modded biomes.
		spawnBiomes = ["minecraft:taiga", "minecraft:wooded_hills", "minecraft:jungle_edge", "minecraft:giant_tree_taiga", "minecraft:flower_forest", "minecraft:dark_forest", "minecraft:snowy_taiga_mountains", "minecraft:tall_birch_hills", "minecraft:taiga_hills", "minecraft:giant_spruce_taiga_hills", "minecraft:birch_forest_hills", "minecraft:dark_forest_hills", "minecraft:forest", "minecraft:swamp_hills", "minecraft:snowy_taiga", "minecraft:tall_birch_forest", "minecraft:swamp", "minecraft:birch_forest", "minecraft:giant_tree_taiga_hills", "minecraft:wooded_mountains", "minecraft:giant_spruce_taiga", "minecraft:taiga_mountains", "minecraft:snowy_taiga_hills"]

